# Base image
FROM node:22-alpine AS base

# Set environment variables
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

# Set the working directory
WORKDIR /app

# Copy the package files
COPY package*.json ./

# Install production dependencies
RUN npm install --silent --no-progress

# Copy the application source code
COPY . .

# Expose the port
EXPOSE 4200

# Start the application (--host [IP_ADDRESS] to be accessible outside the container)
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]